//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Profile
{
    public partial class Manage_WordOfDay
    {
        /// <summary>
 /// EnglishWordTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox EnglishWordTextBox;

     /// <summary>
        /// rfvEnglishWord control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvEnglishWord;

        /// <summary>
        /// PronunciationTextBox control.
        /// </summary>
   protected global::System.Web.UI.WebControls.TextBox PronunciationTextBox;

   /// <summary>
        /// BengaliMeaningTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox BengaliMeaningTextBox;

        /// <summary>
        /// rfvBengaliMeaning control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvBengaliMeaning;

        /// <summary>
        /// PartOfSpeechDropDown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList PartOfSpeechDropDown;

        /// <summary>
    /// ExampleSentenceTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox ExampleSentenceTextBox;

        /// <summary>
        /// AddWordButton control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button AddWordButton;

/// <summary>
   /// MessageLabel control.
        /// </summary>
      protected global::System.Web.UI.WebControls.Label MessageLabel;

        /// <summary>
        /// WordsGridView control.
        /// </summary>
        protected global::System.Web.UI.WebControls.GridView WordsGridView;

        /// <summary>
        /// WordsSQL control.
        /// </summary>
     protected global::System.Web.UI.WebControls.SqlDataSource WordsSQL;
    }
}
