//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Authority.Institutions
{


    public partial class Reset_Institution_Data
    {

        /// <summary>
        /// SchoolDropDown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList SchoolDropDown;

        /// <summary>
        /// SchoolInfoLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label SchoolInfoLabel;

        /// <summary>
        /// ActionPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ActionPanel;

        /// <summary>
        /// FullConfirmTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox FullConfirmTextBox;

        /// <summary>
        /// SessionDropDown control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList SessionDropDown;

        /// <summary>
        /// SessionConfirmTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox SessionConfirmTextBox;

        /// <summary>
        /// PurgeConfirmIdTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PurgeConfirmIdTextBox;

        /// <summary>
        /// PurgeConfirmWordTextBox control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox PurgeConfirmWordTextBox;

        /// <summary>
        /// MsgLabel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label MsgLabel;
    }
}
