-- Check Student table structure
SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Student'
ORDER BY ORDINAL_POSITION

-- Also check what date columns exist
SELECT COLUMN_NAME 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_NAME = 'Student'
AND (COLUMN_NAME LIKE '%Date%' OR COLUMN_NAME LIKE '%Admission%' OR COLUMN_NAME LIKE '%Enroll%')
