//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Committee
{
    public partial class DonationTemplates
    {
        protected global::System.Web.UI.WebControls.DropDownList MemberTypeDropDownList;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator1;
        protected global::System.Web.UI.WebControls.SqlDataSource MemberTypeSQL;
        protected global::System.Web.UI.WebControls.DropDownList CategoryDropDownList;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;
        protected global::System.Web.UI.WebControls.SqlDataSource CategorySQL;
        protected global::System.Web.UI.WebControls.TextBox AmountTextBox;
        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator3;
        protected global::System.Web.UI.WebControls.Button AddTemplateButton;
        protected global::System.Web.UI.WebControls.GridView TemplatesGridView;
        protected global::System.Web.UI.WebControls.SqlDataSource TemplatesSQL;
    }
}
