//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Committee
{
    public partial class Donor_Details
    {
        protected global::System.Web.UI.WebControls.FormView DonorInfoFV;
        protected global::System.Web.UI.WebControls.FileUpload PhotoUploadControl;
        protected global::System.Web.UI.WebControls.SqlDataSource DonorDetailsSQL;
    }
}
