//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Student.Exam {


    public partial class Cumulative_Exam {

        /// <summary>
        /// Cum_ExamDropDownList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.DropDownList Cum_ExamDropDownList;

        /// <summary>
        /// CumiExamSQL control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.SqlDataSource CumiExamSQL;

        /// <summary>
        /// HiddenTeacherSign control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField HiddenTeacherSign;

        /// <summary>
        /// HiddenPrincipalSign control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HiddenField HiddenPrincipalSign;

        /// <summary>
        /// ResultPanel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel ResultPanel;

        /// <summary>
        /// ResultRepeater control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater ResultRepeater;
    }
}

