//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Student.Exam {


    public partial class Individual_Exam {

        protected global::System.Web.UI.UpdatePanel UpdatePanel2;

        protected global::System.Web.UI.WebControls.DropDownList ExamDropDownList;

        protected global::System.Web.UI.WebControls.SqlDataSource ExamNameSQl;

        protected global::System.Web.UI.WebControls.RequiredFieldValidator RequiredFieldValidator2;

        protected global::System.Web.UI.WebControls.Panel IndividualResultPanel;

        protected global::System.Web.UI.UpdateProgress UpdateProgress;
    }
}
