//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Attendances.Online_Display
{
    public partial class Attendance_Slider
    {
        protected global::System.Web.UI.UpdatePanel UpdatePanel1;

        protected global::System.Web.UI.WebControls.CheckBoxList Employee_CheckBoxList;

        protected global::System.Web.UI.WebControls.LinkButton Reload_LinkButton;

        protected global::System.Web.UI.WebControls.Repeater EmployeeScheduleSummaryRepeater;

        protected global::System.Web.UI.WebControls.SqlDataSource EmployeeScheduleSummarySQL;

        protected global::System.Web.UI.WebControls.Repeater EmployeeIN_Repeater;

        protected global::System.Web.UI.WebControls.SqlDataSource Emp_INSQL;

        protected global::System.Web.UI.WebControls.Repeater EmployeeOUT_Repeater;

        protected global::System.Web.UI.WebControls.SqlDataSource Emp_OUTSQL;

        protected global::System.Web.UI.WebControls.CheckBoxList Student_CheckBoxList;

        protected global::System.Web.UI.WebControls.Repeater StudentScheduleSummaryRepeater;

        protected global::System.Web.UI.WebControls.SqlDataSource StudentScheduleSummarySQL;

        protected global::System.Web.UI.WebControls.Repeater StudentINRepeater;

        protected global::System.Web.UI.WebControls.SqlDataSource Student_Entry_LogSQL;

        protected global::System.Web.UI.WebControls.Repeater StudentOUTRepeater;

        protected global::System.Web.UI.WebControls.SqlDataSource Student_Exit_LogSQL;

        protected global::System.Web.UI.UpdateProgress UpdateProgress;
    }
}
