//------------------------------------------------------------------------------

// <auto-generated>

//     This code was generated by a tool.

//

//     Changes to this file may cause incorrect behavior and will be lost if

//     the code is regenerated. 

// </auto-generated>

//------------------------------------------------------------------------------



namespace EDUCATION.COM.Attendances.Online_Display

{

    public partial class DeviceDisplay

    {

        protected global::System.Web.UI.HtmlControls.HtmlForm form1;



        protected global::System.Web.UI.WebControls.Repeater StudentScheduleSummaryRepeater;



        protected global::System.Web.UI.WebControls.SqlDataSource StudentScheduleSummarySQL;



        protected global::System.Web.UI.WebControls.Repeater EmployeeScheduleSummaryRepeater;



        protected global::System.Web.UI.WebControls.SqlDataSource EmployeeScheduleSummarySQL;



        protected global::System.Web.UI.WebControls.Repeater StudentEntryLog;



        protected global::System.Web.UI.WebControls.SqlDataSource Student_Entry_LogSQL;



        protected global::System.Web.UI.WebControls.Repeater StudentExitLog;



        protected global::System.Web.UI.WebControls.SqlDataSource Student_Exit_LogSQL;



        protected global::System.Web.UI.WebControls.Repeater EmployeeEntryLog;



        protected global::System.Web.UI.WebControls.SqlDataSource EmployeeEntryLogSQL;



        protected global::System.Web.UI.WebControls.Repeater EmployeeExitLog;



        protected global::System.Web.UI.WebControls.SqlDataSource EmployeeExitLogSQL;

    }

}

