//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Profile.Invoice
{
    public partial class ShurjoPayCallback
    {
        protected global::System.Web.UI.WebControls.Label lblOrderId;
        protected global::System.Web.UI.WebControls.Label lblAmount;
        protected global::System.Web.UI.WebControls.Label lblMethod;
        protected global::System.Web.UI.WebControls.Label lblTrxId;
        protected global::System.Web.UI.WebControls.Label lblDate;
        protected global::System.Web.UI.WebControls.Label lblStatus;
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
