//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Exam
{
    public partial class AllClassTopMeritBangla
    {
        protected global::System.Web.UI.WebControls.DropDownList EduYearDropDownList;
        protected global::System.Web.UI.WebControls.SqlDataSource EduYearSQL;
        protected global::System.Web.UI.WebControls.DropDownList ExamDropDownList;
        protected global::System.Web.UI.WebControls.SqlDataSource ExamSQL;
        protected global::System.Web.UI.WebControls.RadioButtonList MeritViewRadioButtonList;
        protected global::System.Web.UI.WebControls.Label SchoolNameLabel;
        protected global::System.Web.UI.WebControls.Label SchoolAddressLabel;
        protected global::System.Web.UI.WebControls.Label ExamSessionLabel;
        protected global::System.Web.UI.WebControls.Label MeritListLabel;
        protected global::System.Web.UI.WebControls.Panel ResultsPanel;
        protected global::System.Web.UI.WebControls.Repeater ClassMeritRepeater;
        protected global::System.Web.UI.WebControls.Label EmptyLabel;
    }
}
