//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.Authority
{
    public partial class Bulk_Client_SMS
    {
        protected global::System.Web.UI.WebControls.Panel DevModePanel;
        protected global::System.Web.UI.WebControls.Panel ResultPanel;
        protected global::System.Web.UI.WebControls.Label ResultLabel;
        protected global::System.Web.UI.WebControls.TextBox SearchTextBox;
        protected global::System.Web.UI.WebControls.DropDownList ValidationFilter;
        protected global::System.Web.UI.WebControls.Button FindButton;
        protected global::System.Web.UI.WebControls.Button ClearButton;
        protected global::System.Web.UI.WebControls.Label TotalCountLabel;
        protected global::System.Web.UI.WebControls.Label ActiveCountLabel;
        protected global::System.Web.UI.WebControls.Label DeactiveCountLabel;
        protected global::System.Web.UI.WebControls.Label SmsBalanceLabel;
        protected global::System.Web.UI.WebControls.Label ActiveProviderLabel;
        protected global::System.Web.UI.WebControls.TextBox MessageTextBox;
        protected global::System.Web.UI.WebControls.Button SelectAllButton;
        protected global::System.Web.UI.WebControls.Button ClearSelectionButton;
        protected global::System.Web.UI.WebControls.Button SendButton;
        protected global::System.Web.UI.WebControls.GridView SchoolGridView;
    }
}
