//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDUCATION.COM.ATTENDANCES
{


    public partial class Leave_Type_Settings
    {

        protected global::System.Web.UI.WebControls.TextBox LeaveTypeTextBox;

        protected global::System.Web.UI.WebControls.Button AddButton;

        protected global::System.Web.UI.WebControls.Label MessageLabel;

        protected global::System.Web.UI.WebControls.GridView LeaveTypeGridView;
    }
}
